# Configuration globale de Personal Finance.
languages:
  - id: fr
    label: Français
    icon: 🇫🇷
    locale: fr_FR.UTF-8
    date-format: jj/mm/yy
  - id: de
    label: Deutsch
    icon: 🇩🇪
    locale: de_DE.UTF-8
    date-format: jj/mm/yy
  - id: nl
    label: Nederlands
    icon: 🇳🇱
    locale: nl_NL.UTF-8
    date-format: jj/mm/yy
  - id: en
    label: English
    icon: 🇬🇧
    locale: en_US.UTF-8
    date-format: mm/dd/yy

security:
  only-https: false
  max-upload: 5242880
  max-account: 25
  max-daily-new-account: 5
  zip-max-files: 200
  zip-max-uncompressed-factor: 5
  zip-max-compression-ratio: 100
